# Site settings
title: AI Village
email: contact@aivillage.org
description: >-
  A community of hackers and data scientists working to educate the world 
  on the use and abuse of artificial intelligence in security and privacy.
baseurl: ""
url: "https://aivillage.org"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  events:
    output: true
    permalink: /:collection/:name/
  volunteers:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "AI Village"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# SEO
twitter:
  username: aivillage_dc
  card: summary

social:
  name: AI Village
  links:
    - https://twitter.com/aivillage_dc
    - https://github.com/aivillage